import type { Metadata } from 'next';
import Link from 'next/link';
import { Geist, Geist_Mono } from 'next/font/google';
import { getCurrentUser } from '@/lib/auth';
import './globals.css';

export const dynamic = 'force-dynamic';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          margin: 0,
          background: '#f8fafc',
          minHeight: '100vh',
        }}
      >
        <header
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            height: '64px',
            background: '#ffffff',
            borderBottom: '1px solid #e5e7eb',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '0 24px',
            zIndex: 10,
          }}
        >
          <div style={{ fontWeight: 600, fontSize: '1rem', color: '#111827' }}>
            Dinodia Smart Cloud
          </div>
          <nav style={{ display: 'flex', gap: '16px', fontSize: '0.9rem' }}>
            <Link href="/" style={{ color: '#111827', textDecoration: 'none' }}>
              Home
            </Link>
            <Link
              href="/households"
              style={{ color: '#111827', textDecoration: 'none' }}
            >
              Households
            </Link>
            <Link
              href="/households/new"
              style={{ color: '#111827', textDecoration: 'none' }}
            >
              Register household
            </Link>
            <Link
              href="/register"
              style={{ color: '#2563eb', textDecoration: 'none' }}
            >
              Register
            </Link>
          </nav>
          <div style={{ fontSize: '0.85rem', color: '#111827' }}>
            {user ? (
              <span style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                <span>
                  Logged in as {user.email} ({user.role})
                </span>
                <a
                  href="/api/dev-logout"
                  style={{ color: '#2563eb', textDecoration: 'none' }}
                >
                  Logout
                </a>
              </span>
            ) : (
              <div style={{ display: 'flex', gap: '12px' }}>
                <Link
                  href="/login"
                  style={{ color: '#2563eb', textDecoration: 'none' }}
                >
                  Login
                </Link>
                <Link
                  href="/register"
                  style={{ color: '#2563eb', textDecoration: 'none' }}
                >
                  Register
                </Link>
              </div>
            )}
          </div>
        </header>
        <main style={{ paddingTop: '80px', minHeight: '100vh' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
